# Generated by Django 3.1.7 on 2021-03-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
    ]
