# Generated by Django 3.1.7 on 2021-03-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0003_auto_20210325_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], default='Male', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
    ]
